# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating_type', models.CharField(choices=[('accuracy', 'Accuracy'), ('precision', 'Precision')], default='accuracy', max_length=15)),
                ('rating', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.Profile')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('score', models.CharField(blank=True, max_length=15, null=True)),
                ('score_type', models.CharField(choices=[('undefined', 'Undefined'), ('user_trust', 'User Trust Score'), ('statement_trust', 'Statement Trust Score'), ('statementlink_trust', 'StatementLink Trust Score'), ('underverified', 'Unververified Statements Score')], default='undefined', max_length=20)),
                ('algorithm_version', models.CharField(blank=True, max_length=20, null=True)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
