# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=5000, null=True)),
                ('link', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements_added', to='accounts.Profile')),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='StatementLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contains', 'is contained by'), ('attributes', 'provides attribution for'), ('verifies', 'verifies')], default='verifies', max_length=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statementlinks_added', to='accounts.Profile')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='statements.Statement')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='statements.Statement')),
            ],
        ),
        migrations.AddField(
            model_name='statement',
            name='linked_statements',
            field=models.ManyToManyField(related_name='linked_to', through='statements.StatementLink', to='statements.Statement'),
        ),
    ]
