# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('member', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.BooleanField(default=False)),
                ('claimant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('claimant_bio', models.CharField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('vetted_member', models.BooleanField(default=False)),
                ('date_vetted', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_claimants', to='accounts.Profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
